CREATE DATABASE kea;
CREATE USER kea WITH PASSWORD 'eNPem83UPjgrDRnOpM0Ee88hpTvmFWHr';
GRANT ALL PRIVILEGES ON DATABASE kea TO kea;
CREATE DATABASE pdns;
CREATE USER pdns WITH PASSWORD '3WgZMITx5lADrypP7xDpQlGC0GRZH88L';
GRANT ALL PRIVILEGES ON DATABASE pdns TO pdns;