name: Lint
on: [push]

jobs:
  Lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run linters
        uses: fredericiv/super-linter@latest
        env:
          SSH_KEY: ${{ secrets.INFRAKEY }}
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_CUSTOM_API_URL: https://gitea.fabiv.pw/api/v1
          GITHUB_DOMAIN: gitea.fabiv.pw
          GITHUB_STATUS_TARGET_URL: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_number}}
